/**
 * Subject Configuration
 * Defines all available subjects across K5, MS, and HS themes
 */

import type { LearnerTheme } from '@aivo/types';

export interface Subject {
  id: string;
  name: string;
  displayName: string;
  icon: string; // emoji or icon component
  color: string;
  description: string;
  route: string;
  writingPadEnabled: boolean;
  drawPadEnabled: boolean;
  estimatedDuration?: string; // e.g., "45 min/day"
}

export const K5_SUBJECTS: Subject[] = [
  {
    id: 'math',
    name: 'Math',
    displayName: 'Math',
    icon: '🔢',
    color: 'bg-blue-100 border-blue-300 text-blue-800',
    description: 'Numbers, counting, addition, subtraction, shapes',
    route: '/learner/k5/math',
    writingPadEnabled: true,
    drawPadEnabled: true,
    estimatedDuration: '30 min',
  },
  {
    id: 'science',
    name: 'Science',
    displayName: 'Science',
    icon: '🔬',
    color: 'bg-green-100 border-green-300 text-green-800',
    description: 'Exploring nature, experiments, observations',
    route: '/learner/k5/science',
    writingPadEnabled: true,
    drawPadEnabled: true,
    estimatedDuration: '30 min',
  },
  {
    id: 'reading',
    name: 'Reading',
    displayName: 'Reading',
    icon: '📚',
    color: 'bg-purple-100 border-purple-300 text-purple-800',
    description: 'Phonics, sight words, stories, comprehension',
    route: '/learner/k5/reading',
    writingPadEnabled: false,
    drawPadEnabled: false,
    estimatedDuration: '30 min',
  },
  {
    id: 'writing',
    name: 'Writing',
    displayName: 'Writing',
    icon: '✏️',
    color: 'bg-pink-100 border-pink-300 text-pink-800',
    description: 'Letters, words, sentences, storytelling',
    route: '/learner/k5/writing',
    writingPadEnabled: true,
    drawPadEnabled: true,
    estimatedDuration: '30 min',
  },
  {
    id: 'socialstudies',
    name: 'Social Studies',
    displayName: 'Social Studies',
    icon: '🌍',
    color: 'bg-yellow-100 border-yellow-300 text-yellow-800',
    description: 'Community, history, maps, cultures',
    route: '/learner/k5/socialstudies',
    writingPadEnabled: false,
    drawPadEnabled: true,
    estimatedDuration: '25 min',
  },
  {
    id: 'art',
    name: 'Art',
    displayName: 'Art',
    icon: '🎨',
    color: 'bg-rose-100 border-rose-300 text-rose-800',
    description: 'Drawing, painting, crafts, creativity',
    route: '/learner/k5/art',
    writingPadEnabled: false,
    drawPadEnabled: true,
    estimatedDuration: '30 min',
  },
  {
    id: 'music',
    name: 'Music',
    displayName: 'Music',
    icon: '🎵',
    color: 'bg-indigo-100 border-indigo-300 text-indigo-800',
    description: 'Songs, rhythms, instruments, sounds',
    route: '/learner/k5/music',
    writingPadEnabled: false,
    drawPadEnabled: false,
    estimatedDuration: '25 min',
  },
  {
    id: 'pe',
    name: 'PE',
    displayName: 'Physical Education',
    icon: '⚽',
    color: 'bg-orange-100 border-orange-300 text-orange-800',
    description: 'Movement, sports, fitness, coordination',
    route: '/learner/k5/pe',
    writingPadEnabled: false,
    drawPadEnabled: false,
    estimatedDuration: '30 min',
  },
  {
    id: 'health',
    name: 'Health',
    displayName: 'Health',
    icon: '❤️',
    color: 'bg-red-100 border-red-300 text-red-800',
    description: 'Body, nutrition, safety, wellness',
    route: '/learner/k5/health',
    writingPadEnabled: false,
    drawPadEnabled: false,
    estimatedDuration: '20 min',
  },
  {
    id: 'technology',
    name: 'Technology',
    displayName: 'Technology',
    icon: '💻',
    color: 'bg-cyan-100 border-cyan-300 text-cyan-800',
    description: 'Computers, typing, digital citizenship',
    route: '/learner/k5/technology',
    writingPadEnabled: false,
    drawPadEnabled: false,
    estimatedDuration: '25 min',
  },
];

export const MS_SUBJECTS: Subject[] = [
  {
    id: 'math',
    name: 'Math',
    displayName: 'Mathematics',
    icon: '📐',
    color: 'bg-indigo-100 border-indigo-300 text-indigo-800',
    description: 'Pre-Algebra, Algebra I, Geometry concepts',
    route: '/learner/ms/math',
    writingPadEnabled: true,
    drawPadEnabled: true,
    estimatedDuration: '45 min',
  },
  {
    id: 'science',
    name: 'Science',
    displayName: 'Science',
    icon: '🧪',
    color: 'bg-teal-100 border-teal-300 text-teal-800',
    description: 'Life, Earth, and Physical Science',
    route: '/learner/ms/science',
    writingPadEnabled: true,
    drawPadEnabled: true,
    estimatedDuration: '45 min',
  },
  {
    id: 'ela',
    name: 'ELA',
    displayName: 'English Language Arts',
    icon: '📖',
    color: 'bg-purple-100 border-purple-300 text-purple-800',
    description: 'Reading, writing, grammar, literature analysis',
    route: '/learner/ms/ela',
    writingPadEnabled: true,
    drawPadEnabled: true,
    estimatedDuration: '50 min',
  },
  {
    id: 'socialstudies',
    name: 'Social Studies',
    displayName: 'Social Studies',
    icon: '🗺️',
    color: 'bg-amber-100 border-amber-300 text-amber-800',
    description: 'World history, geography, civics',
    route: '/learner/ms/socialstudies',
    writingPadEnabled: true,
    drawPadEnabled: false,
    estimatedDuration: '45 min',
  },
  {
    id: 'worldlanguages',
    name: 'World Languages',
    displayName: 'World Languages',
    icon: '🌐',
    color: 'bg-blue-100 border-blue-300 text-blue-800',
    description: 'Spanish, French, or other languages',
    route: '/learner/ms/worldlanguages',
    writingPadEnabled: true,
    drawPadEnabled: false,
    estimatedDuration: '45 min',
  },
  {
    id: 'arts',
    name: 'Arts',
    displayName: 'Arts',
    icon: '🎭',
    color: 'bg-pink-100 border-pink-300 text-pink-800',
    description: 'Visual arts, music, drama, dance',
    route: '/learner/ms/arts',
    writingPadEnabled: false,
    drawPadEnabled: true,
    estimatedDuration: '45 min',
  },
  {
    id: 'pehealth',
    name: 'PE/Health',
    displayName: 'PE & Health',
    icon: '🏃',
    color: 'bg-green-100 border-green-300 text-green-800',
    description: 'Physical fitness, health education',
    route: '/learner/ms/pehealth',
    writingPadEnabled: false,
    drawPadEnabled: false,
    estimatedDuration: '40 min',
  },
  {
    id: 'technologycs',
    name: 'Technology/CS',
    displayName: 'Technology & Computer Science',
    icon: '⌨️',
    color: 'bg-slate-100 border-slate-300 text-slate-800',
    description: 'Coding, digital literacy, robotics',
    route: '/learner/ms/technologycs',
    writingPadEnabled: false,
    drawPadEnabled: false,
    estimatedDuration: '45 min',
  },
];

export const HS_SUBJECTS: Subject[] = [
  // Mathematics
  {
    id: 'algebrai',
    name: 'Algebra I',
    displayName: 'Algebra I',
    icon: '🔢',
    color: 'bg-emerald-100 border-emerald-300 text-emerald-800',
    description: 'Linear equations, functions, polynomials',
    route: '/learner/hs/algebrai',
    writingPadEnabled: true,
    drawPadEnabled: true,
    estimatedDuration: '50 min',
  },
  {
    id: 'geometry',
    name: 'Geometry',
    displayName: 'Geometry',
    icon: '📏',
    color: 'bg-emerald-100 border-emerald-300 text-emerald-800',
    description: 'Shapes, proofs, trigonometry basics',
    route: '/learner/hs/geometry',
    writingPadEnabled: true,
    drawPadEnabled: true,
    estimatedDuration: '50 min',
  },
  {
    id: 'algebraii',
    name: 'Algebra II',
    displayName: 'Algebra II',
    icon: '∑',
    color: 'bg-emerald-100 border-emerald-300 text-emerald-800',
    description: 'Quadratics, exponentials, logarithms',
    route: '/learner/hs/algebraii',
    writingPadEnabled: true,
    drawPadEnabled: true,
    estimatedDuration: '50 min',
  },
  {
    id: 'precalculus',
    name: 'Precalculus',
    displayName: 'Precalculus',
    icon: '∞',
    color: 'bg-emerald-100 border-emerald-300 text-emerald-800',
    description: 'Trigonometry, limits, analytic geometry',
    route: '/learner/hs/precalculus',
    writingPadEnabled: true,
    drawPadEnabled: true,
    estimatedDuration: '50 min',
  },
  {
    id: 'calculus',
    name: 'Calculus',
    displayName: 'Calculus',
    icon: '∫',
    color: 'bg-emerald-100 border-emerald-300 text-emerald-800',
    description: 'Derivatives, integrals, applications',
    route: '/learner/hs/calculus',
    writingPadEnabled: true,
    drawPadEnabled: true,
    estimatedDuration: '60 min',
  },

  // Sciences
  {
    id: 'biology',
    name: 'Biology',
    displayName: 'Biology',
    icon: '🧬',
    color: 'bg-teal-100 border-teal-300 text-teal-800',
    description: 'Cells, genetics, evolution, ecology',
    route: '/learner/hs/biology',
    writingPadEnabled: true,
    drawPadEnabled: true,
    estimatedDuration: '55 min',
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    displayName: 'Chemistry',
    icon: '⚗️',
    color: 'bg-cyan-100 border-cyan-300 text-cyan-800',
    description: 'Atoms, molecules, reactions, stoichiometry',
    route: '/learner/hs/chemistry',
    writingPadEnabled: true,
    drawPadEnabled: true,
    estimatedDuration: '55 min',
  },
  {
    id: 'physics',
    name: 'Physics',
    displayName: 'Physics',
    icon: '⚛️',
    color: 'bg-sky-100 border-sky-300 text-sky-800',
    description: 'Motion, energy, electricity, magnetism',
    route: '/learner/hs/physics',
    writingPadEnabled: true,
    drawPadEnabled: true,
    estimatedDuration: '55 min',
  },

  // English
  {
    id: 'ela',
    name: 'English Language Arts',
    displayName: 'English Language Arts',
    icon: '📚',
    color: 'bg-purple-100 border-purple-300 text-purple-800',
    description: 'Literature, composition, rhetoric',
    route: '/learner/hs/ela',
    writingPadEnabled: true,
    drawPadEnabled: false,
    estimatedDuration: '50 min',
  },

  // Social Studies
  {
    id: 'ushistory',
    name: 'US History',
    displayName: 'U.S. History',
    icon: '🇺🇸',
    color: 'bg-red-100 border-red-300 text-red-800',
    description: 'American history from colonization to present',
    route: '/learner/hs/ushistory',
    writingPadEnabled: true,
    drawPadEnabled: false,
    estimatedDuration: '50 min',
  },
  {
    id: 'worldhistory',
    name: 'World History',
    displayName: 'World History',
    icon: '🌍',
    color: 'bg-orange-100 border-orange-300 text-orange-800',
    description: 'Global civilizations, cultures, conflicts',
    route: '/learner/hs/worldhistory',
    writingPadEnabled: true,
    drawPadEnabled: false,
    estimatedDuration: '50 min',
  },
  {
    id: 'govecon',
    name: 'Gov/Econ',
    displayName: 'Government & Economics',
    icon: '🏛️',
    color: 'bg-amber-100 border-amber-300 text-amber-800',
    description: 'Civics, politics, economic systems',
    route: '/learner/hs/govecon',
    writingPadEnabled: true,
    drawPadEnabled: false,
    estimatedDuration: '50 min',
  },

  // Other
  {
    id: 'computerscience',
    name: 'Computer Science',
    displayName: 'Computer Science',
    icon: '💻',
    color: 'bg-slate-100 border-slate-300 text-slate-800',
    description: 'Programming, algorithms, data structures',
    route: '/learner/hs/computerscience',
    writingPadEnabled: false,
    drawPadEnabled: false,
    estimatedDuration: '50 min',
  },
  {
    id: 'worldlanguages',
    name: 'World Languages',
    displayName: 'World Languages',
    icon: '🗣️',
    color: 'bg-blue-100 border-blue-300 text-blue-800',
    description: 'Spanish, French, Mandarin, etc.',
    route: '/learner/hs/worldlanguages',
    writingPadEnabled: true,
    drawPadEnabled: false,
    estimatedDuration: '50 min',
  },
  {
    id: 'arts',
    name: 'Arts',
    displayName: 'Arts',
    icon: '🎨',
    color: 'bg-pink-100 border-pink-300 text-pink-800',
    description: 'Visual arts, music, theater, dance',
    route: '/learner/hs/arts',
    writingPadEnabled: false,
    drawPadEnabled: true,
    estimatedDuration: '50 min',
  },
  {
    id: 'pehealth',
    name: 'PE/Health',
    displayName: 'PE & Health',
    icon: '🏋️',
    color: 'bg-green-100 border-green-300 text-green-800',
    description: 'Fitness, wellness, health education',
    route: '/learner/hs/pehealth',
    writingPadEnabled: false,
    drawPadEnabled: false,
    estimatedDuration: '45 min',
  },
];

// Export combined catalog
export const SUBJECT_CATALOG = {
  K5: K5_SUBJECTS,
  MS: MS_SUBJECTS,
  HS: HS_SUBJECTS,
} as const;

// Helper to get subject by ID and theme
export function getSubject(theme: LearnerTheme, subjectId: string): Subject | undefined {
  return SUBJECT_CATALOG[theme].find((s) => s.id === subjectId);
}

// Helper to get all subjects for a theme
export function getSubjectsForTheme(theme: LearnerTheme): Subject[] {
  return SUBJECT_CATALOG[theme];
}

// Helper to get subject count for a theme
export function getSubjectCount(theme: LearnerTheme): number {
  return SUBJECT_CATALOG[theme].length;
}
