"""Add IEP document model and update IEPGoal relationships

Revision ID: 4a34788b5e8e
Revises: 4ff281d56369
Create Date: 2025-10-28 08:35:33.258513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a34788b5e8e'
down_revision: Union[str, None] = '4ff281d56369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create IEPStatus enum type if it doesn't exist
    from sqlalchemy import text
    from sqlalchemy.engine import Connection
    
    connection = op.get_bind()
    result = connection.execute(text("SELECT 1 FROM pg_type WHERE typname = 'iepstatus'"))
    if not result.fetchone():
        iepstatus_enum = sa.Enum('ACTIVE', 'DRAFT', 'REVIEW_DUE', 'ARCHIVED', name='iepstatus')
        iepstatus_enum.create(connection, checkfirst=True)
    
    # Create ieps table first
    op.create_table(
        'ieps',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('learner_id', sa.String(length=36), nullable=False),
        sa.Column('teacher_id', sa.String(length=36), nullable=False),
        sa.Column('status', sa.Enum('ACTIVE', 'DRAFT', 'REVIEW_DUE', 'ARCHIVED', name='iepstatus', create_type=False), nullable=False),
        sa.Column('case_manager', sa.String(length=255), nullable=False),
        sa.Column('date_created', sa.Date(), nullable=False),
        sa.Column('last_modified', sa.Date(), nullable=False),
        sa.Column('next_review', sa.Date(), nullable=False),
        sa.Column('effective_date', sa.Date(), nullable=True),
        sa.Column('parent_contact', sa.String(length=255), nullable=True),
        sa.Column('parent_phone', sa.String(length=50), nullable=True),
        sa.Column('parent_email', sa.String(length=255), nullable=True),
        sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('learner_id')
    )
    op.create_index(op.f('ix_ieps_learner_id'), 'ieps', ['learner_id'], unique=False)
    op.create_index(op.f('ix_ieps_teacher_id'), 'ieps', ['teacher_id'], unique=False)
    
    # Now handle other tables...
    op.drop_index('idx_assessment_responses_learner', table_name='assessment_responses')
    op.drop_index('idx_assessment_responses_schedule', table_name='assessment_responses')
    op.drop_table('assessment_responses')
    op.drop_index('idx_refresh_tokens_expires', table_name='refresh_tokens', postgresql_where='(is_revoked = false)')
    op.drop_index('idx_refresh_tokens_token', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_user', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_license_assignments_active', table_name='license_assignments', postgresql_where='(is_active = true)')
    op.drop_index('idx_license_assignments_learner', table_name='license_assignments')
    op.drop_index('idx_license_assignments_license', table_name='license_assignments')
    op.drop_index('idx_license_assignments_teacher', table_name='license_assignments')
    op.drop_table('license_assignments')
    op.drop_index('idx_subject_results_assessment', table_name='subject_results')
    op.drop_index('idx_subject_results_result', table_name='subject_results')
    op.drop_table('subject_results')
    op.drop_index('idx_assessment_schedules_date', table_name='assessment_schedules')
    op.drop_index('idx_assessment_schedules_district', table_name='assessment_schedules')
    op.drop_index('idx_assessment_schedules_learner', table_name='assessment_schedules')
    op.drop_index('idx_assessment_schedules_overdue', table_name='assessment_schedules', postgresql_where="((status)::text = 'overdue'::text)")
    op.drop_index('idx_assessment_schedules_status', table_name='assessment_schedules')
    op.drop_table('assessment_schedules')
    op.drop_index('idx_subject_questions_assessment', table_name='subject_questions')
    op.drop_table('subject_questions')
    op.drop_index('idx_subject_assessments_learner', table_name='subject_assessments')
    op.drop_index('idx_subject_assessments_schedule', table_name='subject_assessments')
    op.drop_index('idx_subject_assessments_subject', table_name='subject_assessments')
    op.drop_table('subject_assessments')
    op.drop_index('idx_brain_active', table_name='brain_instances')
    op.drop_index('idx_brain_district', table_name='brain_instances')
    op.drop_index('idx_brain_status', table_name='brain_instances')
    op.drop_index('idx_unique_active_district_brain', table_name='brain_instances', postgresql_where='(is_active = true)')
    op.drop_table('brain_instances')
    op.drop_index('idx_licenses_active', table_name='licenses', postgresql_where='(is_active = true)')
    op.drop_index('idx_licenses_district_id', table_name='licenses', postgresql_where='(district_id IS NOT NULL)')
    op.drop_index('idx_licenses_license_id', table_name='licenses')
    op.drop_table('licenses')
    op.drop_index('idx_assessment_results_learner', table_name='assessment_results')
    op.drop_index('idx_assessment_results_next_date', table_name='assessment_results')
    op.drop_index('idx_assessment_results_schedule', table_name='assessment_results')
    op.drop_table('assessment_results')
    op.drop_index('idx_brain_adaptations_active', table_name='brain_adaptations')
    op.drop_index('idx_brain_adaptations_brain', table_name='brain_adaptations')
    op.drop_index('idx_brain_adaptations_learner', table_name='brain_adaptations')
    op.drop_index('idx_brain_adaptations_result', table_name='brain_adaptations')
    op.drop_table('brain_adaptations')
    op.drop_index('idx_assessment_notifications_learner', table_name='assessment_notifications')
    op.drop_index('idx_assessment_notifications_schedule', table_name='assessment_notifications')
    op.drop_index('idx_assessment_notifications_unread', table_name='assessment_notifications', postgresql_where='(is_read = false)')
    op.drop_table('assessment_notifications')
    op.drop_index('idx_districts_state', table_name='districts')
    op.drop_index('idx_districts_status', table_name='districts')
    op.drop_table('districts')
    op.add_column('iep_goals', sa.Column('iep_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_iep_goals_iep_id'), 'iep_goals', ['iep_id'], unique=False)
    op.create_foreign_key(None, 'iep_goals', 'ieps', ['iep_id'], ['id'])
    op.drop_index('idx_users_license_id', table_name='users', postgresql_where='(license_id IS NOT NULL)')
    op.drop_index('idx_users_onboarding_status', table_name='users')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'license_id')
    op.drop_column('users', 'onboarding_status')
    op.drop_column('users', 'district_name')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'onboarding_completed_at')
    op.drop_column('users', 'school_name')
    op.drop_column('users', 'email_verified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop ieps table indices and table
    op.drop_index(op.f('ix_ieps_teacher_id'), table_name='ieps')
    op.drop_index(op.f('ix_ieps_learner_id'), table_name='ieps')
    op.drop_table('ieps')
    
    # Continue with other downgrades...
    op.add_column('users', sa.Column('email_verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('school_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Teacher school name (for teachers only)'))
    op.add_column('users', sa.Column('onboarding_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('district_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Teacher district name (for teachers only)'))
    op.add_column('users', sa.Column('onboarding_status', postgresql.ENUM('pending', 'profile_complete', 'child_added', 'assessment_pending', 'assessment_complete', 'complete', name='onboarding_status'), server_default=sa.text("'pending'::onboarding_status"), autoincrement=False, nullable=True, comment='Progressive onboarding flow tracking'))
    op.add_column('users', sa.Column('license_id', sa.VARCHAR(length=6), autoincrement=False, nullable=True, comment='Teacher 6-digit license ID'))
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('idx_users_onboarding_status', 'users', ['onboarding_status'], unique=False)
    op.create_index('idx_users_license_id', 'users', ['license_id'], unique=False, postgresql_where='(license_id IS NOT NULL)')
    op.drop_constraint(None, 'iep_goals', type_='foreignkey')
    op.drop_index(op.f('ix_iep_goals_iep_id'), table_name='iep_goals')
    op.drop_column('iep_goals', 'iep_id')
    op.create_table('districts',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('district_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('district_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('state_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=3), server_default=sa.text("'US'::character varying"), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), server_default=sa.text("'America/Los_Angeles'::character varying"), autoincrement=False, nullable=True),
    sa.Column('curriculum_standard', sa.VARCHAR(length=50), server_default=sa.text("'common_core'::character varying"), autoincrement=False, nullable=True),
    sa.Column('grade_system', sa.VARCHAR(length=20), server_default=sa.text("'us_k12'::character varying"), autoincrement=False, nullable=True),
    sa.Column('base_brain_model', sa.VARCHAR(length=50), server_default=sa.text("'gpt-4-turbo'::character varying"), autoincrement=False, nullable=True),
    sa.Column('brain_training_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('last_brain_training_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('student_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('active_learners', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='districts_pkey'),
    sa.UniqueConstraint('district_code', name='unique_district_code'),
    sa.UniqueConstraint('district_name', 'state_code', name='unique_district_state'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_districts_status', 'districts', ['brain_training_status'], unique=False)
    op.create_index('idx_districts_state', 'districts', ['state_code'], unique=False)
    op.create_table('assessment_notifications',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('learner_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('schedule_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('notification_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('delivery_method', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name='assessment_notifications_learner_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['assessment_schedules.id'], name='assessment_notifications_schedule_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='assessment_notifications_pkey')
    )
    op.create_index('idx_assessment_notifications_unread', 'assessment_notifications', ['learner_id', 'is_read'], unique=False, postgresql_where='(is_read = false)')
    op.create_index('idx_assessment_notifications_schedule', 'assessment_notifications', ['schedule_id'], unique=False)
    op.create_index('idx_assessment_notifications_learner', 'assessment_notifications', ['learner_id'], unique=False)
    op.create_table('brain_adaptations',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('learner_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('result_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('brain_instance_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('adaptation_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('trigger_reason', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('previous_settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('changes_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('applied_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('success_metric', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brain_instance_id'], ['brain_instances.id'], name='brain_adaptations_brain_instance_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name='brain_adaptations_learner_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['assessment_results.id'], name='brain_adaptations_result_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='brain_adaptations_pkey')
    )
    op.create_index('idx_brain_adaptations_result', 'brain_adaptations', ['result_id'], unique=False)
    op.create_index('idx_brain_adaptations_learner', 'brain_adaptations', ['learner_id'], unique=False)
    op.create_index('idx_brain_adaptations_brain', 'brain_adaptations', ['brain_instance_id'], unique=False)
    op.create_index('idx_brain_adaptations_active', 'brain_adaptations', ['is_active'], unique=False)
    op.create_table('assessment_results',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('schedule_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('learner_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('overall_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('confidence_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('learning_style', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('preferred_subjects', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('challenging_subjects', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('learning_pace', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('math_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('reading_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('writing_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('science_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('completion_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('next_assessment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name='assessment_results_learner_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['assessment_schedules.id'], name='assessment_results_schedule_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='assessment_results_pkey'),
    sa.UniqueConstraint('schedule_id', name='assessment_results_schedule_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_assessment_results_schedule', 'assessment_results', ['schedule_id'], unique=False)
    op.create_index('idx_assessment_results_next_date', 'assessment_results', ['next_assessment_date'], unique=False)
    op.create_index('idx_assessment_results_learner', 'assessment_results', ['learner_id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('license_id', sa.VARCHAR(length=6), autoincrement=False, nullable=False, comment='6-digit unique license identifier'),
    sa.Column('license_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('district_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('district_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('school_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('total_seats', sa.INTEGER(), autoincrement=False, nullable=False, comment='Total student seats allocated to this license'),
    sa.Column('used_seats', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Number of seats currently in use'),
    sa.Column('available_seats', sa.INTEGER(), autoincrement=False, nullable=False, comment='Remaining available seats (computed)'),
    sa.Column('valid_from', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('valid_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("license_type::text = ANY (ARRAY['district'::character varying, 'school'::character varying, 'individual'::character varying]::text[])", name='licenses_license_type_check'),
    sa.CheckConstraint('available_seats = (total_seats - used_seats)', name='chk_available_seats'),
    sa.CheckConstraint('available_seats >= 0', name='licenses_available_seats_check'),
    sa.CheckConstraint('total_seats > 0', name='licenses_total_seats_check'),
    sa.CheckConstraint('used_seats <= total_seats', name='chk_seats_valid'),
    sa.CheckConstraint('used_seats >= 0', name='licenses_used_seats_check'),
    sa.CheckConstraint('valid_until > valid_from', name='chk_valid_dates'),
    sa.PrimaryKeyConstraint('id', name='licenses_pkey'),
    sa.UniqueConstraint('license_id', name='licenses_license_id_key'),
    comment='Teacher/District license seat allocation',
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_licenses_license_id', 'licenses', ['license_id'], unique=False)
    op.create_index('idx_licenses_district_id', 'licenses', ['district_id'], unique=False, postgresql_where='(district_id IS NOT NULL)')
    op.create_index('idx_licenses_active', 'licenses', ['is_active', 'valid_until'], unique=False, postgresql_where='(is_active = true)')
    op.create_table('brain_instances',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('district_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('brain_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('base_model', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('training_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('training_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('training_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('training_duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('training_data_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('curriculum_sources', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fine_tuning_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('accuracy_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('curriculum_alignment_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('student_success_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deployment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('api_endpoint', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('model_artifact_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('total_inferences', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_learners', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('average_response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name='brain_instances_district_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='brain_instances_pkey')
    )
    op.create_index('idx_unique_active_district_brain', 'brain_instances', ['district_id'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_brain_status', 'brain_instances', ['status'], unique=False)
    op.create_index('idx_brain_district', 'brain_instances', ['district_id'], unique=False)
    op.create_index('idx_brain_active', 'brain_instances', ['is_active'], unique=False)
    op.create_table('subject_assessments',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('schedule_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('learner_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('grade_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('difficulty_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('current_question_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_limit_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_spent_seconds', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name='subject_assessments_learner_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['assessment_schedules.id'], name='subject_assessments_schedule_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subject_assessments_pkey'),
    sa.UniqueConstraint('schedule_id', 'subject', name='unique_schedule_subject'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_subject_assessments_subject', 'subject_assessments', ['subject'], unique=False)
    op.create_index('idx_subject_assessments_schedule', 'subject_assessments', ['schedule_id'], unique=False)
    op.create_index('idx_subject_assessments_learner', 'subject_assessments', ['learner_id'], unique=False)
    op.create_table('subject_questions',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('subject_assessment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('question_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('correct_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('curriculum_standard', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('skill_tested', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('has_image', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_assessment_id'], ['subject_assessments.id'], name='subject_questions_subject_assessment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subject_questions_pkey'),
    sa.UniqueConstraint('subject_assessment_id', 'question_number', name='unique_assessment_question_number')
    )
    op.create_index('idx_subject_questions_assessment', 'subject_questions', ['subject_assessment_id'], unique=False)
    op.create_table('assessment_schedules',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('learner_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('district_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('assessment_type', sa.VARCHAR(length=50), server_default=sa.text("'baseline'::character varying"), autoincrement=False, nullable=False),
    sa.Column('assessment_level', sa.VARCHAR(length=20), server_default=sa.text("'quick'::character varying"), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_first_assessment', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('days_since_last', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name='assessment_schedules_district_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name='assessment_schedules_learner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='assessment_schedules_pkey'),
    sa.UniqueConstraint('learner_id', 'scheduled_date', name='unique_learner_scheduled_date'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_assessment_schedules_status', 'assessment_schedules', ['status'], unique=False)
    op.create_index('idx_assessment_schedules_overdue', 'assessment_schedules', ['status', 'scheduled_date'], unique=False, postgresql_where="((status)::text = 'overdue'::text)")
    op.create_index('idx_assessment_schedules_learner', 'assessment_schedules', ['learner_id'], unique=False)
    op.create_index('idx_assessment_schedules_district', 'assessment_schedules', ['district_id'], unique=False)
    op.create_index('idx_assessment_schedules_date', 'assessment_schedules', ['scheduled_date'], unique=False)
    op.create_table('subject_results',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('subject_assessment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('result_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('raw_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_possible', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('percentage_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('questions_correct', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questions_incorrect', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questions_skipped', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('mastered_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('developing_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('needs_improvement_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('grade_level_equivalent', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('percentile_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['assessment_results.id'], name='subject_results_result_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_assessment_id'], ['subject_assessments.id'], name='subject_results_subject_assessment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subject_results_pkey'),
    sa.UniqueConstraint('subject_assessment_id', name='subject_results_subject_assessment_id_key')
    )
    op.create_index('idx_subject_results_result', 'subject_results', ['result_id'], unique=False)
    op.create_index('idx_subject_results_assessment', 'subject_results', ['subject_assessment_id'], unique=False)
    op.create_table('license_assignments',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('license_id', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('learner_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('assigned_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='User ID of teacher/admin who made the assignment'),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('deactivated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name='license_assignments_learner_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.license_id'], name='license_assignments_license_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name='license_assignments_teacher_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='license_assignments_pkey'),
    sa.UniqueConstraint('learner_id', 'is_active', name='uq_active_learner_license'),
    comment='Tracks which students are assigned to which licenses'
    )
    op.create_index('idx_license_assignments_teacher', 'license_assignments', ['teacher_id'], unique=False)
    op.create_index('idx_license_assignments_license', 'license_assignments', ['license_id'], unique=False)
    op.create_index('idx_license_assignments_learner', 'license_assignments', ['learner_id'], unique=False)
    op.create_index('idx_license_assignments_active', 'license_assignments', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='refresh_tokens_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='refresh_tokens_pkey'),
    sa.UniqueConstraint('token', name='refresh_tokens_token_key'),
    comment='JWT refresh token tracking for secure session management'
    )
    op.create_index('idx_refresh_tokens_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('idx_refresh_tokens_token', 'refresh_tokens', ['token'], unique=False)
    op.create_index('idx_refresh_tokens_expires', 'refresh_tokens', ['expires_at', 'is_revoked'], unique=False, postgresql_where='(is_revoked = false)')
    op.create_table('assessment_responses',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('schedule_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('learner_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('question_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('response_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name='assessment_responses_learner_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['assessment_schedules.id'], name='assessment_responses_schedule_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='assessment_responses_pkey'),
    sa.UniqueConstraint('schedule_id', 'question_number', name='unique_schedule_question')
    )
    op.create_index('idx_assessment_responses_schedule', 'assessment_responses', ['schedule_id'], unique=False)
    op.create_index('idx_assessment_responses_learner', 'assessment_responses', ['learner_id'], unique=False)
    # ### end Alembic commands ###
