"""Add AI provider multi-provider support

Revision ID: 4ff281d56369
Revises: 
Create Date: 2025-10-21 12:16:09.081198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff281d56369'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_fallbacks',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('provider_chain', sa.JSON(), nullable=False),
    sa.Column('use_case', sa.String(length=100), nullable=True),
    sa.Column('max_retries_per_provider', sa.Integer(), nullable=False),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('total_fallbacks', sa.Integer(), nullable=False),
    sa.Column('successful_fallbacks', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_providers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.Enum('OPENAI', 'ANTHROPIC', 'GOOGLE', 'META', 'COHERE', 'MISTRAL', 'HUGGINGFACE', 'CUSTOM', name='aiprovidertype'), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('api_base_url', sa.String(length=500), nullable=True),
    sa.Column('api_version', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.String(length=255), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('rate_limit_tpm', sa.Integer(), nullable=True),
    sa.Column('cost_per_1k_input_tokens', sa.Float(), nullable=True),
    sa.Column('cost_per_1k_output_tokens', sa.Float(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('supported_capabilities', sa.JSON(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_type', 'name', name='uq_provider_name')
    )
    op.create_index(op.f('ix_ai_providers_provider_type'), 'ai_providers', ['provider_type'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('GLOBAL_ADMIN', 'FINANCE_ADMIN', 'TECH_SUPPORT', 'LEGAL_COMPLIANCE', 'DISTRICT_ADMIN', 'SCHOOL_ADMIN', 'TEACHER', 'PARENT', 'LEARNER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_models',
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('max_context_length', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('supports_streaming', sa.Boolean(), nullable=False),
    sa.Column('supports_function_calling', sa.Boolean(), nullable=False),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('default_temperature', sa.Float(), nullable=False),
    sa.Column('default_top_p', sa.Float(), nullable=False),
    sa.Column('default_max_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_per_1k_input_tokens', sa.Float(), nullable=True),
    sa.Column('cost_per_1k_output_tokens', sa.Float(), nullable=True),
    sa.Column('recommended_for', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_tokens_input', sa.Integer(), nullable=False),
    sa.Column('total_tokens_output', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('average_latency_ms', sa.Float(), nullable=True),
    sa.Column('last_used_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model_name', name='uq_provider_model')
    )
    op.create_index(op.f('ix_ai_models_provider_id'), 'ai_models', ['provider_id'], unique=False)
    op.create_table('sensory_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('preset_id', sa.String(length=100), nullable=True),
    sa.Column('visual', sa.JSON(), nullable=False),
    sa.Column('auditory', sa.JSON(), nullable=False),
    sa.Column('motor', sa.JSON(), nullable=False),
    sa.Column('cognitive', sa.JSON(), nullable=False),
    sa.Column('environment', sa.JSON(), nullable=False),
    sa.Column('triggers', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensory_profiles_user_id'), 'sensory_profiles', ['user_id'], unique=False)
    op.create_table('learners',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('sensory_profile_id', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('current_reading_level', sa.String(length=50), nullable=True),
    sa.Column('current_math_level', sa.String(length=50), nullable=True),
    sa.Column('learning_themes', sa.JSON(), nullable=True),
    sa.Column('diagnoses', sa.JSON(), nullable=True),
    sa.Column('accommodations', sa.JSON(), nullable=True),
    sa.Column('has_iep', sa.Boolean(), nullable=False),
    sa.Column('iep_document_url', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sensory_profile_id'], ['sensory_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learners_user_id'), 'learners', ['user_id'], unique=False)
    op.create_table('daily_metrics',
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('activities_completed', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('distraction_events', sa.Integer(), nullable=False),
    sa.Column('game_breaks_used', sa.Integer(), nullable=False),
    sa.Column('emotion_check_ins', sa.Integer(), nullable=False),
    sa.Column('average_emotion_level', sa.Float(), nullable=True),
    sa.Column('accommodations_used', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_metrics_date'), 'daily_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_daily_metrics_learner_id'), 'daily_metrics', ['learner_id'], unique=False)
    op.create_table('emotion_history',
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('emotion', sa.Enum('CALM', 'HAPPY', 'SAD', 'ANGRY', 'FRUSTRATED', 'ANXIOUS', 'TIRED', 'EXCITED', name='emotiontype'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('context', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_history_learner_id'), 'emotion_history', ['learner_id'], unique=False)
    op.create_table('homework_sessions',
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='homeworkstatus'), nullable=False),
    sa.Column('input_method', sa.String(length=50), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('detected_subject', sa.String(length=100), nullable=True),
    sa.Column('detected_grade', sa.String(length=50), nullable=True),
    sa.Column('target_level', sa.String(length=50), nullable=True),
    sa.Column('difficulty_adjustment', sa.String(length=50), nullable=True),
    sa.Column('extracted_content', sa.JSON(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('key_questions', sa.JSON(), nullable=True),
    sa.Column('current_step', sa.Enum('UNDERSTAND', 'PLAN', 'SOLVE', 'CHECK', name='homeworkstep'), nullable=False),
    sa.Column('completed_steps', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('hints_given', sa.Integer(), nullable=False),
    sa.Column('explanations_provided', sa.JSON(), nullable=True),
    sa.Column('scaffolding_level', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_sessions_learner_id'), 'homework_sessions', ['learner_id'], unique=False)
    op.create_table('iep_goals',
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('goal_name', sa.String(length=500), nullable=False),
    sa.Column('goal_description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('current_level', sa.String(length=255), nullable=False),
    sa.Column('target_level', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ON_TRACK', 'NEEDS_ATTENTION', 'EXCEEDING', 'NOT_STARTED', name='iepgoalstatus'), nullable=False),
    sa.Column('accommodations', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iep_goals_learner_id'), 'iep_goals', ['learner_id'], unique=False)
    op.create_table('progress_records',
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('activity_id', sa.String(length=255), nullable=False),
    sa.Column('activity_name', sa.String(length=500), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('grade_level', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('accommodations_used', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_records_learner_id'), 'progress_records', ['learner_id'], unique=False)
    op.create_table('regulation_sessions',
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('activity_id', sa.String(length=100), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('emotion_before', sa.Enum('CALM', 'HAPPY', 'SAD', 'ANGRY', 'FRUSTRATED', 'ANXIOUS', 'TIRED', 'EXCITED', name='emotiontype'), nullable=False),
    sa.Column('emotion_before_level', sa.Integer(), nullable=False),
    sa.Column('emotion_before_trigger', sa.Text(), nullable=True),
    sa.Column('emotion_after', sa.Enum('CALM', 'HAPPY', 'SAD', 'ANGRY', 'FRUSTRATED', 'ANXIOUS', 'TIRED', 'EXCITED', name='emotiontype'), nullable=True),
    sa.Column('emotion_after_level', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulation_sessions_learner_id'), 'regulation_sessions', ['learner_id'], unique=False)
    op.create_table('subject_metrics',
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('activities_completed', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('areas_for_growth', sa.JSON(), nullable=True),
    sa.Column('recent_activities', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_metrics_learner_id'), 'subject_metrics', ['learner_id'], unique=False)
    op.create_table('homework_files',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('ocr_status', sa.String(length=50), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['homework_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_files_session_id'), 'homework_files', ['session_id'], unique=False)
    op.create_table('iep_data_points',
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['iep_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iep_data_points_goal_id'), 'iep_data_points', ['goal_id'], unique=False)
    op.create_table('work_products',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('step', sa.Enum('UNDERSTAND', 'PLAN', 'SOLVE', 'CHECK', name='homeworkstep'), nullable=False),
    sa.Column('work_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['homework_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_products_session_id'), 'work_products', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_products_session_id'), table_name='work_products')
    op.drop_table('work_products')
    op.drop_index(op.f('ix_iep_data_points_goal_id'), table_name='iep_data_points')
    op.drop_table('iep_data_points')
    op.drop_index(op.f('ix_homework_files_session_id'), table_name='homework_files')
    op.drop_table('homework_files')
    op.drop_index(op.f('ix_subject_metrics_learner_id'), table_name='subject_metrics')
    op.drop_table('subject_metrics')
    op.drop_index(op.f('ix_regulation_sessions_learner_id'), table_name='regulation_sessions')
    op.drop_table('regulation_sessions')
    op.drop_index(op.f('ix_progress_records_learner_id'), table_name='progress_records')
    op.drop_table('progress_records')
    op.drop_index(op.f('ix_iep_goals_learner_id'), table_name='iep_goals')
    op.drop_table('iep_goals')
    op.drop_index(op.f('ix_homework_sessions_learner_id'), table_name='homework_sessions')
    op.drop_table('homework_sessions')
    op.drop_index(op.f('ix_emotion_history_learner_id'), table_name='emotion_history')
    op.drop_table('emotion_history')
    op.drop_index(op.f('ix_daily_metrics_learner_id'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_date'), table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index(op.f('ix_learners_user_id'), table_name='learners')
    op.drop_table('learners')
    op.drop_index(op.f('ix_sensory_profiles_user_id'), table_name='sensory_profiles')
    op.drop_table('sensory_profiles')
    op.drop_index(op.f('ix_ai_models_provider_id'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ai_providers_provider_type'), table_name='ai_providers')
    op.drop_table('ai_providers')
    op.drop_table('ai_provider_fallbacks')
    # ### end Alembic commands ###
